[project]
name = "AI-HR"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Gr", email = "gavrilov_ga@bk.ru"},
]
dependencies = ["fastapi>=0.116.0", "uvicorn>=0.35.0", "authx>=1.4.3"]
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
