[project]
name = "AI-HR"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Gr", email = "gavrilov_ga@bk.ru"},
]
dependencies = []
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
